version: 0.2

phases:
  build:
    commands:
      - mkdir -p artifact/app
      - cp index.html artifact/app/
      - cp app.js artifact/app/
      - cp appspec.yml artifact/
      - mkdir -p artifact/scripts
      - cp scripts/*.sh artifact/scripts/

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - app/**/*
  discard-paths: no
